openapi: 3.0.0
info:
  title: Movie Quotes
  description: Movie Quotes API
  version: 0.1.9

servers:
  - url: https://folksoul-api.nika-nozadze.redberryinternship.ge/api
    description: production server
  - url: http://localhost:4000/api
    description: local server  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /users/new:
    post:
      tags:
        - Users  
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: 'object'
              properties:
                  name: 
                    type: string
                  password: 
                    type: string
                  repeatPassword:
                    type: string
                  email:
                    type: string
            example:
              name: nikanoza
              password: astarta16
              repeatPassword: astarta16
              email: nikanozadze1010@gmail.com
      responses:
        '201':
          description: user register successfully